CREATE TYPE order_status AS ENUM ('Pendente', 'Pago', 'Enviado', 'Entregue', 'Cancelado');

CREATE TABLE "products"(
    "id" UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "price" DECIMAL(8, 2) NOT NULL,
    "stock" INTEGER NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "customers" (
  "id" UUID NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  "first_name" TEXT,
  "last_name" TEXT,
  "address" TEXT
);

CREATE TABLE "orders"(
    "id" UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
    "customer_id" UUID NOT NULL REFERENCES "customers"("id"),
    "total" DECIMAL(8, 2) NOT NULL,
    "status" order_status NOT NULL DEFAULT 'Pendente',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "order_items"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "order_id" UUID NOT NULL REFERENCES "orders"("id"),
    "product_id" UUID NOT NULL REFERENCES "products"("id"),
    "quantity" INTEGER NOT NULL,
    "unit_price" DECIMAL(8, 2) NOT NULL
);